### ISSUE TITLE
Não haverá integração nem mesmo com um sistema de mapas ou e-mail, por exemplo?

### ISSUE THREAD

**Issue by tmsasaki** [brbelarmino1/ppads-projeto-05J#1]

**Comment by brbelarmino1** [comment]
Reformulada as integrações com sistemas externos. 

Incluímos um mapa para busca de geolocalização.

**Comment by brbelarmino1** [comment]
Adicionamos a comunicação com a ferramenta de e-mail para disparo automático quando houver cadastro de novos usuários/fornecedores.
